cmd/zed/permission.go

Signed-off-by: Jake Moshenko <jacob.moshenko@gmail.com>

add support for lookup

---

.github/workflows/build.yaml
.github/workflows/release.yaml
.goreleaser.yml
Dockerfile
Dockerfile.release

goreleaser expects to use the binaries it already built

use goreleaser to publish docker images

---

.github/workflows/release.yaml
.goreleaser.yml

this also fixes an issue with the mac binary name

Use authzedbot to publish homebrew tap

---

.github/workflows/release.yaml
.goreleaser.yml

separate jobs can't coordinate on uploading to releases by name

pass mac build to goreleaser

---

cmd/zed/relationship.go

Fix building of the read relationships call in zed

---

cmd/zed/context.go
cmd/zed/experiment.go
cmd/zed/import.go
cmd/zed/main.go
cmd/zed/permission.go
cmd/zed/relationship.go
cmd/zed/schema.go
internal/storage/config.go
internal/storage/secrets.go

Store insecure in the context and use automatically if present

---

.goreleaser.yml

See: https://goreleaser.com/customization/changelog/#changelog

use github native changelog generator

---

.goreleaser.docker.yml

This reverts an accidental regression in #155.

goreleaser: use alpine base for debug images

---

internal/commands/relationship.go

https://github.com/authzed/zed/issues/189

--caveat split issue with caveatname and json

---

cmd/zed/main.go
internal/client/client.go
internal/commands/watch.go
internal/console/console.go
pkg/wasm/client.go

this is useful to test the Watch API and validate
behaviour of a client application that will use the API

introduce watch command

---

go.mod
pkg/wasm/main.go
pkg/wasm/main_test.go

Also adds a test to ensure encoding and decoding matches the expected form

Fix caveat context encoding by using protojson

---

.github/workflows/build-test.yaml
.github/workflows/cla.yaml
.github/workflows/lint.yaml

the merge queue should make the experience to merge dependabot PRs smoother

update GitHub Actions to leverage merge queue

---

internal/client/client.go
internal/cmd/context.go
internal/storage/secrets.go

Allow storage of --no-verify-ca on contexts, similar to insecure

---

internal/backupformat/backupformat_test.go
internal/backupformat/decoder.go
internal/backupformat/encoder.go
internal/backupformat/schema.go
internal/cmd/backup.go
internal/cmd/restore.go

Backup zedtoken

---

internal/commands/relationship.go

it didn't indicate subject relation is possible

Improve CLI help for relationship commands

---

internal/commands/relationship.go

it's backward compatible with SpiceDB instances
that do not support pagination, and does this by
not asking for another page if the page size was
bigger than the limit.
Tested with SpiceDB 1.24.0 and 1.19.0
Sets the default page size to 100

update read relationships to use pagination

---

internal/cmd/validate.go
internal/printers/treeprinter.go

Add explain traces to assertion failure output and fix line offsets

---

go.mod
go.sum
internal/cmd/context.go

Adds dynamic completion on `zed context use`
Fixes #66

Add dynamic shell completion support to zed for context use

---

internal/cmd/cmd.go

Fix typo in helper text for --certificate-path

---

internal/cmd/context.go

context: add autocomplete for remove

---

internal/commands/permission.go

the command look like
```
zed permission bulk <tuple1> <tuple2>
```
supports the json flag and consistency flags
The CLI accepts items as tuples so it can include a caveat context. The `--caveat-context` flag is not supported

add check bulk support in zed

---

internal/commands/permission.go

1) Fix documentation
2) Add nil check for the parse call

Fixes for bulk check command

---

internal/cmd/context.go
internal/commands/permission.go

Support command shorthands

---

.github/workflows/lint.yaml
.github/workflows/release.yaml

Something the goreleaser maintainer asked for. He wants to see whether this fix will work.
* Bump to nightly build
Review

Use new build of goreleaser

---

README.md

Making the conversation in #421 more explicit. This provides the documentation; that PR can be about some code refactoring.
Add a README section on overriding context
Review.

Add some documentation about overriding context

---

.github/workflows/lint.yaml
.golangci.yaml
internal/printers/debug.go

v2 recently came out and has breaking changes around config. This gets us onto v2.
* Migrate config
* Use alternate workflow
* Fix issues
Review. See that tests pass.

Use golangci-lint v2

---

internal/cmd/validate-test/missing-relation.yaml
internal/cmd/validate.go
internal/cmd/validate_test.go

fix positioning of error when schema isn't first section

---

internal/client/client.go
internal/client/client_test.go

fixes https://github.com/authzed/zed/issues/504

do not retry import bulk

---

.github/workflows/docs.yaml
docs/zed.md

Fix https://github.com/authzed/zed/actions/runs/14786594930/job/41516017532

update docs and fix docs workflow

---

README.md

Fixes #517 
A user pointed this out; this fixes the readme.
* Update readme accordingly
Review.

Update yum installation instructions

---

docs/getting-started.md
docs/zed.md

Pulling over updates made to the destination doc

Update docs components with latest changes from docs site
