authzed/zed

- internal/printers/table.go
The `PrintTable` function ignores its `io.Writer` argument, always printing to `os.Stdout` instead.
Fix this by using the argument.
Addresses #21
> fix(printers): print to target writer

- .goreleaser.yml
Unfortunately, goreleaser doesn't like top-level keys that it doesn't know about.
> avoid top-level keys in goreleaser

- .github/workflows/release.yaml
- .goreleaser.yml
dist is gitignored, so goreleaser won't complain about a dirty tree
> move mac build into dist

- .goreleaser.yml
not clear why the previous wasn't finding it, goreleaser didn't have any logs related to extra_files
> Find darwin release by glob

- .goreleaser.yml
If a prebuilt `zed` can't be found, this will build from source.
> add head build to brew formula

- go.mod
- go.sum
- internal/grpcutil/grpcutil.go
This also updates authzed-go to use the default of 0 instead of -1 when trailers are not present.
> cmd: trailers only log debug, add tracing

- cmd/zed/import.go
Following this change, `zed import` now supports two modes for handling prefixes:
1) A new CLI flag `--schema-definition-prefix` which will automatically rewrite the schema and test relationships with that prefix
2) If not specified, `zed import` will first call `ReadSchema` for the permissions system and, if a prefix is found, use that prefix automatically
Fixes #81
> Have `zed import` automatically handle prefixing when applicable

- cmd/zed/import.go
- go.mod
- internal/grpcutil/batch.go
- internal/grpcutil/batch_test.go
supersedes https://github.com/authzed/zed/pull/95
closes https://github.com/authzed/zed/issues/94
This PR implements a more testable variant of batching than the one presented in https://github.com/authzed/zed/pull/95. The default batch size is 1000 records with 1 worker. A single worker renders the import synchronous, making parallel processing opt-in.
> Add batching functionality

- cmd/zed/schema.go
- cmd/zed/schema_test.go
This was originally made strict before SpiceDB allowed multiple prefixes; now it is too strict
Fixes #131
> Relax automatic prefix handling to allow multiple prefixes

- cmd/zed/main.go
- cmd/zed/version.go
The version command now makes a ReadSchema call to the service, and prints out the version returned (if any)
Fixes #132
> Have `zed version` print the service version as well

- .goreleaser.docker.yml
- Dockerfile
- Dockerfile.release
Fixes https://github.com/authzed/zed/issues/141
I've basically ported changes in https://github.com/authzed/spicedb/pull/750
- I've also updated `Dockerfile` to use distroless.dev/static. The original PR did not update that file.
- I've noticed the `build` section of `.goreleaser.docker.yaml` deviates from the one in SpiceDB. I've left untouched, but wonder if we should align them
> add debug image variants

- .goreleaser.docker.yml
We need distroless.dev/alpine-base for libs that zed links
Fixes #151
> Fix goreleaser config so that we use the proper base image

- .github/workflows/release.yaml
- .goreleaser.docker.yml
- .goreleaser.yml
This disables CGO in release containers, which fixes the issue where the binary cannot be found.
Fixes #151
> Fix broken release images

- internal/commands/schema.go
- pkg/wasm/main.go
- pkg/wasm/main_test.go
1) Always reconstruct the command to not store help state
2) Fix the description of the schema command
3) Remove version command from WASM
> Small improvements for WASM

- pkg/wasm/main.go
- pkg/wasm/main_test.go
Without the `ResetFlags` call (recursively), calling a command with `--help` causes the flag to be "sticky" for all subsequent invocations
See: https://github.com/spf13/cobra/issues/1488
> Call ResetFlags recursively to fix the reuse of the root command in WASM

- internal/commands/relationship.go
- internal/commands/relationship_test.go
Closes https://github.com/authzed/zed/issues/198
the `zed relationship read` command missed caveat context
> add caveat context to relationship read output

- cmd/zed/context.go
- cmd/zed/validate.go
- cmd/zed/version.go
- internal/client/client.go
- internal/commands/schema.go
- internal/storage/secrets.go
This commit vastly improves the file keyring to
- only prompt once per execution
- specify when creating a password
Fixes #197
> internal/secrets: fix headless file keyring

- go.mod
- go.sum
- internal/cmd/schema_test.go
- internal/commands/permission.go
- internal/commands/relationship_test.go
- internal/decode/decoder_test.go
- internal/grpcutil/batch_test.go
- internal/printers/debug.go
- internal/printers/tree.go
- internal/printers/treeprinter.go
- internal/printers/treeprinter_test.go
despite CRDB's treeprinter converting to Apache 2.0 after the Change Date, the community reported friction on adopting `zed` because automated tools would flag BSL incompatible with Apache 2.0.
This commit replaces cockroachdb treeprinter with
github.com/xlab/treeprint.
It's a mostly 1:1 migration, except due to the design choice to always create an implicit empty root node. I addressed that by removing that implicit root node after the tree is populated, as unfortunately the printer is unable to realize we are starting the print process from an intermediate node. To hide that complexity I wrapped it in our own type.
> replaces cockroachdb treeprinter with github.com/xlab/treeprint

- internal/cmd/cmd.go
- internal/cmd/import.go
- internal/cmd/schema.go
- internal/cmd/schema_test.go
- internal/cmd/validate.go
- internal/cmd/version.go
- internal/commands/permission.go
- internal/commands/relationship.go
- internal/commands/schema.go
- internal/grpcutil/grpcutil.go
- pkg/wasm/main.go
certain operations may take long to execute, e.g. `ReadRelationships` with a very wide relation. The current behaviour is to completely ignore process termination via something like Control+C, and zed will continue to block until `SIGKILL` or
the operation completes. It's a jarring experience.
This commit introduces a goroutine the listens to `SIGINT` and cancels the context, which is also now propagated via cobra. This makes the command-line seem responsive when the user terminates it.
> capture SIGINT and fail-fast

- internal/storage/config.go
> Add a more descriptive error message for calling zed without a context

- internal/cmd/schema.go
The check to make sure that stdin is not a terminal was actually checking stdout, meaning that you cannot actually send a schema via stdin. This commit fixes this check.
I noticed this when working on #263 .
> Fix bug when writing schema supplied via stdin

- internal/commands/relationship.go
- internal/commands/relationship_test.go
a potentially common scenario is zed is being invoked from a shell script that is having its input piped, but zed itself is being provided with arguments as the result of parsing that input in the script. In such case arguments provided should take precedence to the STDIN, instead of erroring out
> fixes when STDIN input and CLI args are provided

- internal/cmd/backup.go
- internal/cmd/restore.go
This adds support for passing a single dash character as the filename
to the backup command, resulting in it using stdout.  It also changes
the restore command to default to reading from stdin if no filename is
given.
Fixes: #284
> Support stdout / stdin for backup and restore

- internal/storage/config.go
The context token supports NoVerifyCA and CACert. When it restored the values from a keychain it wasn't mapping the values from the token read to the token returned. This prevented zed client users from benefiting from stored --no-verify-ca and --certificate-path values.
With a simple addition the values are passed from context and they no longer need to be manually set on the command line.
> Add missing context token attributes

- internal/cmd/import.go
- internal/cmd/validate.go
- internal/decode/decoder.go
- internal/decode/decoder_test.go
> Support validate (and import) taking in a schema directly

- go.mod
- go.sum
- internal/cmd/backup.go
- pkg/backupformat/redaction.go
- pkg/backupformat/redaction_test.go
Helpful for providing community support without leaking the names, comments and/or object IDs in the permission system
Related: #194
> Add command for redacting backups

- internal/cmd/cmd.go
This shortcut was missing the autocompletion available in the longform `zed context use`.
> cmd: add autocomplete to `zed use`

- internal/cmd/backup.go
as the Avro encoder wasn't being flushed and
the file may have been partially written
> fixes bug where redacted files may end up corrupted

- internal/cmd/backup.go
- internal/cmd/cmd.go
- internal/cmd/context.go
- internal/cmd/import.go
- internal/cmd/schema.go
- internal/cmd/validate.go
- internal/commands/completion.go
- internal/commands/permission.go
- internal/commands/relationship.go
- internal/commands/schema.go
- internal/commands/watch.go
This PR does a few things
- consistently capitalizes usage text
- disables zsh's default file completion when not applicable
- uses file extensions for completion on schema/validation commands
- uses context completion for `zed schema copy`
> More and less completion

- README.md
if the file `/etc/apt/sources.list.d/fury.list` does not exist the command will fail with `Permission denied`
> fix ubuntu install instructions

- go.mod
- go.sum
- internal/cmd/cmd.go
- internal/commands/util.go
Adds a `--request-id` flag to all `zed` commands. This improves the SpiceDB debugging experience by corrolating a specific request with SpiceDB server logs and OpenTelemetry traces.
> Allow passing request ID

- internal/commands/relationship.go
- internal/commands/relationship_test.go
Fixes a bug in `zed relationship read` where the resource ID argument was not being applied, resulting in an incorrect filtering of relationships.
This regression was introduced by #341, which added filtering using prefixes.
> Respect resource ID filter when reading relationships

- internal/commands/permission.go
Ensures that we nil check the response from a CheckPermission request before attempting to extract the debug info from it.
This regression was introduced in #354 where we added support for the new debug info in the response body rather than in HTTP trailers.
> Fix panic on permission check error

- internal/commands/permission.go
- internal/commands/permission_test.go
Reference: https://github.com/authzed/spicedb/pull/1930
> Add support for reading debug information from the error details

- .github/workflows/release.yaml
- .goreleaser.docker.yml
- .goreleaser.yml
Close #398
https://github.com/authzed/zed/actions/runs/9942983136/job/27465721921
```
Run goreleaser/goreleaser-action@v6
Warning: You are using 'latest' as default version. Will lock to '~> v2'.
Downloading https://github.com/goreleaser/goreleaser-pro/releases/download/v2.1.0-pro/goreleaser-pro_Darwin_all.tar.gz
Extracting GoReleaser
/usr/bin/tar xz -C /Users/runner/work/_temp/a6eaee15-e2ed-4efa-8513-20ad884515ab -f /Users/runner/work/_temp/5997958d-49af-44fc-a94c-5beea7f0be38
GoReleaser latest installed successfully
/Users/runner/hostedtoolcache/goreleaser-action/2.1.0-pro/arm64/goreleaser release --rm-dist
⨯ command failed                                   error=unknown flag: --rm-dist
Error: The process '/Users/runner/hostedtoolcache/goreleaser-action/2.1.0-pro/arm64/goreleaser' …
```
> chore: fix the release error

- pkg/backupformat/redaction.go
- pkg/backupformat/redaction_test.go
wilcards were getting redacted, which then caused
a backup to fail to be restored, because the relationship written was not a wildcard.
> zed backup redact: do not redact wildcards

- internal/cmd/backup.go
so that customers can identify the mapping that
reproduces a specific issue
> backup redact: print objectID redaction mapping

- internal/storage/secrets.go
Fixes #192 
We've gotten reports of users unintentionally setting empty passphrases, either when setting contexts programmatically or unintentionally during setup on their local, and then not knowing what their password is. Forcing a user to set a non-empty passphrase should help with this.
* Pull out a password prompt function
* Add assertion around empty passphrases on creation
Add the following to the `keyring.Config` declaration in `internal/storage/secrets.go`:
```
AllowedBackends: []keyring.BackendType{"file"},
```
This will force it to use the file-based backend.
Build the binary and then run:
```
./zed context set foo foo:50051 sometoken --insecure
```
when it prompts you for a password, leave it empty and see that it errors.
Now repeat and set a non-empty password. Repeat and see …
> Add non-empty passphrase constraint to context keyring

- internal/cmd/cmd.go
Fixes #368 
See #368. For error cases that were about missing commands or invalid argument sets, the logic that set up `zerolog` was never invoked, which meant that the output was a JSON blob instead of the prettily-formatted zerolog output. This makes the output more visually consistent.
* Add `init` to command that sets up logging in the event that `zl.RunE` isn't actually called.
Review. Checkout, `go build cmd/zed/..`, and run the resulting binary with some invalid args. `./main foo` and `./main validate` should do it.
> Add init that sets up logging for exceptional cases

- internal/client/client.go
- internal/cmd/cmd.go
We had a user run into an issue where `zed backup <filename>` failed with:
```
2:08PM ERR terminated with errors error="error receiving relationships: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (6280392 vs. 4194304)"
```
This indicates that the client received a 6mb message with a max configured message size of 4mb, which is the default for a gRPC client.
This seems like something that could reasonably happen with a sufficiently large schema, especially if it has lots of comments.
My understanding is that this is a securityish feature meant to prevent a client from choking on an incoming message. It would also prevent a client from getting OOMkilled as a result of attempting to read a too-large message into memory. For the zed client, it seems like …
> Add option for max message size

- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- .goreleaser.yml
- Dockerfile
- go.mod
- go.sum
- internal/cmd/backup.go
- internal/cmd/backup_test.go
- internal/cmd/restorer.go
- internal/cmd/restorer_test.go
- internal/cmd/schema.go
- internal/cmd/validate.go
- internal/cmd/version.go
- internal/grpcutil/batch.go
- internal/storage/secrets.go
1.22.7 published a security patch. This takes that patch.
Bump go.mod to take patch and fix subsequent lint issues
Review.
> Take security patch

- internal/client/client.go
- internal/client/client_test.go
- internal/cmd/schema.go
- internal/cmd/version.go
- internal/storage/config.go
- internal/storage/config_test.go
- internal/storage/secrets.go
- internal/storage/secrets_test.go
- internal/testing/test_helpers.go
A customer reported flags being ignored even when
they were being provided via CLI arguments.
The behavior of overriding current context via
CLI arguments was inconsistent across the codebase. This centralizes the logic so all the various commands use the same logic.
> fixes context override

- .github/workflows/release.yaml
Fixes #418 
Turns out github actions don't support yaml anchors: actions/runner#1182
This caused the bug reported in the issue.
* Get rid of yaml anchor syntax
Review. Cut a release and see that it succeeds.
> Get rid of anchor syntax in release yaml

- internal/client/client.go
- internal/client/client_test.go
- internal/storage/config.go
- internal/storage/secrets.go
In #417 we introduced a bug where `zed` became unusable if there wasn't previously a context set by the user. This wasn't intentional; it should be valid to invoke zed entirely from the command line in isolation. This PR captures that behavior in a unit test and fixes the behavior.
* Separate existence and fetching concerns for tokens
* Handle cases where config file or token don't exist
See that tests go green. See that you can clear out your local context (or run from within a container): `/zed schema write ./blah.zed --endpoint 127.0.0.1:50051 --token supersecretdevkey --insecure` and not receive an error.
> Fix CLI usage with no pre-set context/config

- internal/commands/permission.go
Fixes #422 
@Hmast3rs pointed out that we were formatting ID before type rather than the other way around in this print call. This fixes that.
* Reverse the order of output
Review. See that things go green.
> Fix print order of relation

- go.mod
- go.sum
- internal/cmd/import.go
- internal/cmd/validate.go
- internal/decode/decoder.go
Related #453 #454
`zed validate` now takes in multiple args to validate, also looks for `schemaFile` in given .yaml validation files to parse the schema. Example usage:-
```
(base) Kartikay2@Kartikays-MacBook-Pro-2 zed % ./zed validate validations/*
warning: Arrow `parent->reader` under permission "view" references relation "reader" on definition "folder"; it is recommended to point to a permission (arrow-references-relation)
25 |       relation auditor: user with day_of_a_week
26 | 
27 | 
28 >       // can user:kartikay view document:quartely_planning
29 |       permission view = reader + owner + parent->reader + auditor
30 |       permission edit = owner + parent->owner
25 |     - "[user:owner_1] is <document:quaterly_planning#owner>"
26 |     - "[user:owner_2] is …
```
> Added multiple validation files parsing support

- .gitignore
- internal/cmd/import.go
- internal/cmd/validate.go
- internal/decode/decoder.go
I noticed that if I validate multiple files, the output looks like `Success!Success!Success!` which isn't ideal. This fixes that and prettifies the output some.
The current approach also reuses the context for relationships, which means that individual validation files share relationships and will step on each others' toes.
* Add go.work files to gitignore
* Reorganize multiple-file loop
* Relax requirement to pass schema as argument
Review. Disable whitespace for a nicer experience. Set up a folder with a few schema files in it and run `go run ./cmd/zed/... validate folder/*` and see that the output looks nice.
> Fixes for zed validate on multiple files

- internal/cmd/import.go
- internal/cmd/import_test.go
- internal/cmd/test/happy-path-validation-file.yaml
- internal/cmd/test/happy-path-validation-schema.zed
- internal/decode/decoder.go
Fixes #460 
This is something that broke in #455 because the interfaces didn't line up. This fixes the behavior of `zed import`.
* Pass in the correct type in the import command's invocation of `decodeUrl`
* Add some defensiveness to the unmarshal logic so that it doesn't panic
* Add a test for the happy path that exercised the failure
Review. Do a `go run ./cmd/zed/... import path/to/some/validationfile.yaml` and see that it either succeeds or fails on the gRPC call (if you aren't running a SpiceDB instance) rather than panicking on the parsing.
> Fix import behavior

- .github/workflows/docs.yaml
- go.mod
- go.sum
- internal/cmd/cmd.go
- magefiles/magefile.go
- magefiles/util.go
Fixes #234 
Added github workflow that would invoke mage to generate docs for zed and submit the changes to the docs repo.
> Added magefile to generate docs with github workflow

- .github/workflows/docs.yaml
- .gitignore
- magefiles/magefile.go
Related #464 workflow and documentation directory update
> docs: update gh workflow and docs dir

- .github/workflows/docs.yaml
I used these perms while debugging the same 403 with an earlier approach, `peter-evans/create-pull-request` action didn't need these perms on my fork (something to do with gh token), should work this time, checked with this just now https://github.com/kartikaysaxena/zed/actions/runs/13248365111/workflow
> workflow: perms updated

- internal/client/client.go
Should fix #475 
Works as per [this](https://github.com/grpc/grpc-go/tree/8c080da92c4baa4bf99e79ab6c30bd70e45120e3/examples/features/name_resolving) (tested locally with socks5 proxy)
> client: bypass endpoint name resolution

- .github/workflows/release-windows.yml
- .goreleaser.windows.yml
Should close #480
Added goreleaser config for windows (similar to that of SpiceDB) with options for chocolatey.
Tested with `goreleaser release --snapshot --clean -f .goreleaser.windows.yml` for a snapshot build which generates chocolatey build files under `dist/`
> goreleaser: add goreleaser config for publishing to chocolatey

- internal/cmd/validate-test/failed-expected-relations.yaml
- internal/cmd/validate-test/warnings.zed
- internal/cmd/validate.go
- internal/cmd/validate_test.go
- internal/printers/treeprinter.go
In preparation for https://github.com/authzed/zed/pull/478, adding more tests to ensure we don't break existing behavior.
> add more validate tests

- go.mod
- internal/client/client.go
- internal/cmd/backup.go
- internal/cmd/backup_test.go
- internal/cmd/import_test.go
- internal/cmd/restorer_test.go
- internal/cmd/schema_test.go
- internal/commands/permission_test.go
- internal/commands/relationship_test.go
- internal/grpcutil/batch_test.go
- internal/storage/secrets.go
- internal/testing/test_helpers.go
- pkg/backupformat/encoder.go
This PR modifies the backup create command to allow an incomplete backup to be resumed.
A new marker file is added with the last written bulk export cursor. This was not added to the OCF file because OCF container is not meant for in-place updates, but streaming append operations. The marker is updated every time a bulk export page is successfully written.
For convenience, the command now also supports creating a backup without a file name; in this case, it will derive the backup file name from the Zed context name. A new `page-limit` flag has also been added to allow users to specify the number of relationships to ingest per page. This may be useful as a mechanism to throttle the number of relationships read from the datastore.
The new logic detects several scenarios like:
- A backup …
> introduce resumable backups

- internal/cmd/validate_test.go
😅 flakiness seen in https://github.com/authzed/zed/actions/runs/14629634822/job/41049218633?pr=496
```
Explanation:
-  ⨉ document:1 viewer (Xµs)
-  └── ⨉ document:1 view (Xµs)
+  ⨉ document:1 viewer (6.196757ms)
+  └── ⨉ document:1 view (6.058769ms)
```
> fix flakey validate test

- go.mod
- internal/client/client.go
- internal/client/client_test.go
- internal/cmd/backup.go
- internal/cmd/cmd.go
Introduces gRPC middleware to do client-side retries by default. The only flag introduced to customize this behaviour is the maximum number of attempts, which defaults to 20.
Retries are enabled for both unary and streaming bot APIs.
https://github.com/user-attachments/assets/f3ba29ba-e995-4ca6-9a85-493e8f94291a
> add client-wide retries

- internal/cmd/backup.go
- internal/cmd/cmd.go
- internal/cmd/cmd_test.go
- internal/cmd/context.go
- internal/cmd/import.go
- internal/cmd/preview.go
- internal/cmd/schema.go
- internal/cmd/validate.go
- internal/commands/permission.go
- internal/commands/relationship.go
- internal/commands/schema.go
- internal/commands/util.go
- internal/commands/util_test.go
- internal/commands/watch.go
Built on top of https://github.com/authzed/zed/pull/492
The usage was being printed on any error, which was rather unpleasant to look at because it made the output difficult to parse for clues on what happened. The primary goal of this commit is to enhance the user experience.
Cobra supports `SilenceErrors` and `SilenceUsage`, as well as a callback function, `SetFlagErrorFunc`, for handling flag parsing errors and controlling when usage and errors are printed. Unfortunately, only a subset of errors fall under the "flag parsing error" category: validation errors defined via `Command.Args` do not trigger `FlagErrorFunc`, so if `SilenceUsage` is enabled, we would miss the usage for those validation cases 😢
To address this, a special error wrapper is introduced that signals an error is a …
> print usage only on parse/validation errors

- internal/cmd/validate-test/composable-schema-root.zed
- internal/cmd/validate-test/composable-schema-user.zed
- internal/cmd/validate-test/composable-schema-warning-root.zed
- internal/cmd/validate-test/external-and-composable.yaml
- internal/cmd/validate-test/only-passes-composable.zed
- internal/cmd/validate.go
- internal/cmd/validate_test.go
- internal/decode/decoder.go
- internal/decode/decoder_test.go
Part of composable schema support. We want to make it so that `zed validate` can operate on both composable schemas and standard schemas.
* By default, `validate` will attempt to validate a schema first according to composable schema rules, then standard schema rules, and if both fail it will show the errors from composable schema.
* There's a new flag: `schema-syntax`. If you add `--schema-syntax composable`, it will validate according to only composable schema syntax rules, and if you add `--schema-syntax standard`, it will validate according to only standard schema rules. The default value for this flag is the empty string.
- Manual testing to ensure no regressions were introduced
- Unit tests
> Add support for composable schemas in `zed validate`

- .goreleaser.windows.yml
Fix failures to release to chocolatey. https://github.com/authzed/zed/actions/runs/14652457878/job/41121211214
```
• running goreleaser v2.3.2-pro (outdated, latest is v2.8.2)
⨯ release failed after 0s                  error=failed to load configuration: yaml: unmarshal errors:
line 24: field formats not found in type config.FormatOverride
```
We use `goreleaser-pro` v2.3.2, the schema is in https://github.com/goreleaser/goreleaser-pro/blob/v2.3.2-pro/pkg/config/config.go.
The same issue exists in https://github.com/authzed/spicedb/actions/runs/14222628747/job/39854249726. If it works here, I will update there too.
> fix typo in goreleaser.windows.yml

- .gitattributes
- .github/workflows/docs.yaml
- .github/workflows/lint.yaml
- .gitignore
- docs/getting-started.md
- docs/zed.md
- magefiles/gen.go
- magefiles/util.go
This PR attempts to make the public-facing docs (https://authzed.com/docs/spicedb/getting-started/installing-zed) more complete by including both installation docs and a reference to all the commands.
The idea:
- `docs/` now contains 2 files
- `getting-started` is what exists today in https://authzed.com/docs/spicedb/getting-started/installing-zed and what exists in today's README (I don't love the duplication 😢 )
- `zed.md` is auto-generated via `mage gen:docs`
Then on every PR, we run `mage gen:docsForPublish` which generates `docs/merged.md` and pushes it to the docs repo.
Run `mage gen:docsForPublish` and look at `docs/merged.md` 😄
> auto-generate more complete docs

- .github/workflows/build-test.yaml
- internal/client/client_test.go
- internal/cmd/backup_test.go
- internal/cmd/cmd_test.go
- internal/cmd/helpers_test.go
- internal/cmd/restorer_test.go
- internal/cmd/schema_test.go
- internal/cmd/validate_test.go
- internal/commands/relationship_test.go
- internal/decode/decoder.go
```sh
C:\Users\mparn\Documents\GitHub\zed (main)
λ go test -race ./... -count=1
?       github.com/authzed/zed/cmd/zed  [no test files]
{"level":"trace","context-override-via-cli":true,"context":{"Name":"","Endpoint":"e1","APIToken":"t1","Insecure":true,"NoVerifyCA":true,"CACert":"aGk="},"time":"2025-05-08T14:58:25-07:00"}
{"level":"trace","context-override-via-cli":false,"context":{"Name":"","Endpoint":"e2","APIToken":"t2","Insecure":false,"NoVerifyCA":false,"CACert":"Ynll"},"time":"2025-05-08T14:58:25-07:00"}
--- FAIL: TestGetTokenWithCLIOverride (1.45s)
testing.go:1267: TempDir RemoveAll cleanup: remove C:\Users\mparn\AppData\Local\Temp\TestGetTokenWithCLIOverride2482217832\001\3569675982: The process cannot access the file because it is being used by another process. …
```
> changes to get the tests to pass on Windows

- internal/cmd/backup.go
- internal/cmd/backup_test.go
- internal/cmd/restorer.go
- internal/cmd/restorer_test.go
> use ImportBulk and ExportBulk instead

- internal/storage/secrets.go
When a system doesn't have a native keyring manager, this is what the current error message is:
```
Setting the environment variable `ZED_KEYRING_PASSWORD` to your password will skip prompts.
Keyring file does not already exist.
Enter a new non-empty passphrase for the new keyring file: 
```
This doesn't explain why this error is popping up, so i've added a line for more details about it. The new message will read:
```
If your platform doesn't have a native keychain manager (e.g. macOS, Linux+GNOME/KDE), ZED_KEYRING_PASSWORD is what's used to encrypt files on disk to store credentials. The first time you create a context, it'll prompt you to create a keyring password to encrypt that configuration.
Keyring file does not already exist.
Enter a new non-empty passphrase for the new keyring …
```
> added a verbose message for keyring error

- internal/cmd/validate-test/schema-with-warnings.zed
- internal/cmd/validate.go
- internal/cmd/validate_test.go
Fixes #536 
This is to provide stricter validation for the folks that want it. This adds a `fail-on-warn` flag that treats warnings as errors, e.g. for CI. This brings zed closer to inline with other linters.
* Add a test for `fail-on-warn`
* Add a `fail-on-warn` flag
Review. See that tests pass. Give me :bike: :house: feedback about the name of the flag.
> Add fail-on-warn flag to validate

- internal/cmd/validate-test/warnings-point-at-right-line.yaml
- internal/cmd/validate-test/warnings-point-at-right-line.zed
- internal/cmd/validate.go
- internal/cmd/validate_test.go
- internal/decode/decoder.go
See #537. zed points at the wrong line when validating the attached schema.
This is a partial fix for the issue; this issue will still manifest in composable schemas. Fixing that problem will require a more substantial rework of composable schema compilation, so we're deferring it for now.
* Write a failing test
* Fix the test by changing the schema reading/compilation behavior
Review. See that tests pass.
> Fix regression in warning output

- .markdownlint.yaml
- docs/getting-started.md
Disabling the first line heading lint rule to accommodate import statements in destination mdx files.
Docs .md files in this repo are processed and used in mdx files in the docs repo. However, mdx files do not
allow html comments so individual line exemptions for markdownlint do not work.
> Disable first-line-heading markdownlint rule
